In [84]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [53]:
from pathlib import Path

folder = Path(r"C:\Users\priya\Music\creditcard.csv")
print([f.name for f in folder.iterdir()])
df = pd.read_csv(r"C:\Users\priya\Music\creditcard.csv\creditcard.csv")

['creditcard.csv']

In [54]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [55]:
df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [57]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [58]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

Separating the data for The Analysis Purpose

In [59]:
legit = df[df.Class == 0]
fraud = df[df.Class == 1]

In [60]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [61]:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [62]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

Compare the valuues for both TRanXXations

In [63]:
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

**Building a sample dataset containing similar distribution of normal transaxxion and fraudulent Transaxxion**

In [64]:
legit_sample = legit.sample(n=492)

In [65]:
new_df = pd.concat([legit_sample, fraud], axis=0)

In [66]:
new_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
208816,137287.0,2.065192,0.005944,-1.620513,0.013658,0.640890,-0.249733,0.153834,-0.175094,0.176103,...,0.280416,0.966943,-0.040801,0.288874,0.342664,-0.132788,-0.018169,-0.064405,1.79,0
202810,134502.0,-1.927348,-0.055020,0.732195,-1.132291,0.603840,-0.378471,-0.342888,0.780163,0.319490,...,0.034562,0.322284,0.919940,0.593050,-0.445582,0.084218,0.264291,0.092987,14.90,0
72316,54654.0,1.314504,-0.890904,1.151131,-0.392964,-1.494284,0.112202,-1.267479,0.243423,0.267436,...,0.014094,0.228959,0.055161,0.091259,0.283546,-0.210993,0.066280,0.018470,1.00,0
107942,70688.0,-0.308783,1.033114,1.793698,1.627342,-0.347440,-0.084807,0.525109,-0.075717,-0.301505,...,-0.139302,-0.186821,-0.044103,0.403248,-0.346484,-0.372995,0.079758,0.144077,28.27,0
153061,97824.0,-0.652371,0.767643,1.400788,-0.807942,0.204449,0.253625,0.094701,-0.857801,1.733890,...,0.867608,0.512174,-0.199097,0.680024,-0.207368,0.016579,0.212611,0.158484,50.00,0

In [67]:
new_df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [68]:
new_df['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [69]:
new_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,95691.367886,0.022069,0.009954,0.141231,-0.039968,0.064842,0.074009,0.035021,0.049528,0.005624,...,0.045104,-0.015649,0.016799,0.012306,-0.013416,0.007252,0.015783,-0.014282,-0.015236,81.638902
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

***Splitting the data into features and targets***

In [70]:
X = new_df.drop(columns="Class")
Y = new_df["Class"]

In [71]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
208816  137287.0  2.065192  0.005944 -1.620513  0.013658  0.640890 -0.249733
202810  134502.0 -1.927348 -0.055020  0.732195 -1.132291  0.603840 -0.378471
72316    54654.0  1.314504 -0.890904  1.151131 -0.392964 -1.494284  0.112202
107942   70688.0 -0.308783  1.033114  1.793698  1.627342 -0.347440 -0.084807
153061   97824.0 -0.652371  0.767643  1.400788 -0.807942  0.204449  0.253625
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
208816  0.153834 -0.175094  0.176103  ... -0.119700  0.280416  0.966943
202810 -0.342888  0.780163  0.319490  ... -0.317680  0.034562  0.322284
72316  -1.267479  0.243423  0.267436  ... -0.058770  0.014094  0.228959
107942  0.525109 -0.075717 -0.301505  ...  0.118107 -0.139302 -0.186821
153061  0.094701 -0.857801  1.733890  ... -0.229616  0.867608  0.512174
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
208816 -0.040801  0.288874  0.342664 -0.132788 -0.018169 -0.064405    1.79
202810  0.919940  0.593050 -0.445582  0.084218  0.264291  0.092987   14.90
72316   0.055161  0.091259  0.283546 -0.210993  0.066280  0.018470    1.00
107942 -0.044103  0.403248 -0.346484 -0.372995  0.079758  0.144077   28.27
153061 -0.199097  0.680024 -0.207368  0.016579  0.212611  0.158484   50.00
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [72]:
print(Y)

208816    0
202810    0
72316     0
107942    0
153061    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

***Split the data into TRaining data & Testing data***

In [73]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.2, stratify=Y, random_state=2)

In [74]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

In [75]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# Splitting data
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y,
    test_size=0.2,
    stratify=Y,
    random_state=2
)

print(X.shape, X_train.shape, X_test.shape)

# Feature scaling
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Model
model = LogisticRegression(max_iter=1000)

# Training
model.fit(X_train, Y_train)

(984, 30) (787, 30) (197, 30)

LogisticRegression(max_iter=1000)

In [76]:
model.fit(X_train, Y_train)

LogisticRegression(max_iter=1000)

***MoDel Evaluation based on accuracy Score***

In [77]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [78]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9567979669631512

***Accuracy on test DATA***

In [79]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [80]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9390862944162437

In [81]:
from sklearn.metrics import precision_score, recall_score, confusion_matrix

print("Precision:", precision_score(Y_test, X_test_prediction))
print("Recall:", recall_score(Y_test, X_test_prediction))
print(confusion_matrix(Y_test, X_test_prediction))

Precision: 0.9886363636363636
Recall: 0.8877551020408163
[[98  1]
 [11 87]]

In [83]:
from sklearn.metrics import precision_score, recall_score, confusion_matrix

print("Precision:", precision_score(Y_test, X_test_prediction))
print("Recall:", recall_score(Y_test, X_test_prediction))
print(confusion_matrix(Y_test, X_test_prediction))

Precision: 0.9886363636363636
Recall: 0.8877551020408163
[[98  1]
 [11 87]]