In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [4]:
df = pd.read_csv('/content/creditcard.csv')

In [5]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [6]:
df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
81294,58872,1.104942,-0.900171,0.271719,-0.528821,-1.064148,-0.533231,-0.366603,-0.121795,-0.855554,...,-0.384664,-0.898500,0.062703,0.098835,-0.024267,0.920347,-0.062583,0.029725,133.76,0.0
81295,58872,-0.438214,0.492120,2.440138,0.454998,-0.148495,0.476077,0.115241,0.232635,-0.057007,...,0.263317,0.865982,-0.093755,-0.026039,-0.602399,-0.453104,0.032011,-0.068108,17.85,0.0
81296,58872,-0.473593,1.109975,1.704117,-0.019309,0.076774,-0.585510,0.718295,-0.023019,-0.619852,...,-0.165078,-0.312285,0.027214,0.417189,-0.266886,0.076342,0.291547,0.123537,0.89,0.0
81297,58873,-2.769864,1.253167,0.752106,0.455407,-1.894425,0.539661,1.081240,-0.188369,1.288851,...,-0.139859,0.276332,0.232680,0.403653,-0.699800,-0.894091,-1.689498,-0.295784,245.00,0.0
81298,58874,1.116529,-0.157694,-0.149952,1.059937,0.256352,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81299 entries, 0 to 81298
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    81299 non-null  int64
 1   V1      81299 non-null  float64
 2   V2      81299 non-null  float64
 3   V3      81299 non-null  float64
 4   V4      81299 non-null  float64
 5   V5      81299 non-null  float64
 6   V6      81298 non-null  float64
 7   V7      81298 non-null  float64
 8   V8      81298 non-null  float64
 9   V9      81298 non-null  float64
 10  V10     81298 non-null  float64
 11  V11     81298 non-null  float64
 12  V12     81298 non-null  float64
 13  V13     81298 non-null  float64
 14  V14     81298 non-null  float64
 15  V15     81298 non-null  float64
 16  V16     81298 non-null  float64
 17  V17     81298 non-null  float64
 18  V18     81298 non-null  float64
 19  V19     81298 non-null  float64
 20  V20     81298 non-null  float64
 21  V21     81298 non-null  float64
 22  V22     81298 non-null  float64
 23  V23     81298 non-null  float64
 24  V24     81298 non-null  float64
 25  V25     81298 non-null  float64
 26  V26     81298 non-null  float64
 27  V27     81298 non-null  float64
 28  V28     81298 non-null  float64
 29  Amount  81298 non-null  float64
 30  Class   81298 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 19.2 MB

In [9]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [10]:
df['Class'].value_counts()

Class
0.0    81100
1.0      198
Name: count, dtype: int64

Separating the data for The Analysis Purpose

In [11]:
legit = df[df.Class == 0]
fraud = df[df.Class == 1]

In [12]:
print(legit.shape)
print(fraud.shape)

(81100, 31)
(198, 31)

In [14]:
legit.Amount.describe()

count    81100.000000
mean        98.107837
std        269.738371
min          0.000000
25%          7.730000
50%         26.990000
75%         89.530000
max      19656.530000
Name: Amount, dtype: float64

In [15]:
fraud.Amount.describe()

count     198.000000
mean       93.992778
std       211.099415
min         0.000000
25%         1.000000
50%         6.410000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

Compare the valuues for both TRanXXations

In [16]:
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,37682.000937,-0.244848,-0.049587,0.701227,0.150821,-0.266673,0.100652,-0.097695,0.045923,-0.005120,...,0.041506,-0.031324,-0.104952,-0.037601,0.008468,0.134375,0.025923,0.000776,0.002077,98.107837
1.0,33363.156566,-6.471142,4.615004,-8.642655,5.163640,-4.726320,-1.982527,-6.839513,3.005157,-3.106588,...,0.381224,0.754921,-0.156429,-0.222226,-0.092181,0.229928,0.089311,0.568505,0.053900,93.992778

**Building a sample dataset containing similar distribution of normal transaxxion and fraudulent Transaxxion**

In [17]:
legit_sample = legit.sample(n=492)

In [18]:
new_df = pd.concat([legit_sample, fraud], axis=0)

In [19]:
new_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
28617,35081,1.085832,-0.019862,1.411139,1.365234,-0.894725,0.092824,-0.580158,0.165906,0.756434,...,-0.004530,0.261025,0.055842,0.417752,0.322363,-0.401656,0.094074,0.039769,9.99,0.0
67912,52749,1.262254,0.321232,0.531876,0.610350,-0.392549,-0.968033,0.126197,-0.259665,-0.099692,...,-0.247007,-0.666458,0.124896,0.400941,0.250625,0.091704,-0.022704,0.020946,1.29,0.0
60324,49276,1.224487,-0.778533,0.780710,-0.783623,-1.140507,-0.060439,-0.942140,0.165095,-0.824985,...,0.184507,0.341897,0.045176,0.027004,0.138127,-0.325971,0.030589,0.019471,50.00,0.0
79322,57968,-6.463284,-7.325641,1.419325,0.701141,3.341705,-3.576497,-2.769595,0.980992,0.769910,...,0.722036,-0.692419,0.485653,0.721629,-0.338047,0.522230,-0.032016,-1.024053,224.32,0.0
70897,54066,-0.655794,-3.946605,-1.131316,0.431895,-2.082825,-0.711262,1.093374,-0.489795,-0.703813,...,0.179981,-1.369590,-0.928052,0.454545,-0.006432,0.982941,-0.279871,0.180625,1073.58,0.0

In [20]:
new_df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
79835,58199,0.340391,2.015233,-2.777330,3.812024,-0.461729,-1.152022,-2.001959,0.548681,-2.344042,...,0.299769,-0.583283,-0.187696,-0.329256,0.732328,0.058080,0.553143,0.318832,1.75,1.0
79874,58217,-0.443794,1.271395,1.206178,0.790371,0.418935,-0.848376,0.917691,-0.235511,-0.285692,...,0.119279,0.513479,-0.264243,0.443311,0.029516,-0.335141,-0.188815,-0.123391,5.09,1.0
79883,58222,-1.322789,1.552768,-2.276921,2.992117,-1.947064,-0.480288,-1.362388,0.953242,-2.329629,...,0.614969,-0.195200,0.590711,-0.233378,-0.164285,-0.277498,0.428610,0.246394,270.00,1.0
80760,58642,-0.451383,2.225147,-4.953050,4.342228,-3.656190,-0.020121,-5.407554,-0.748436,-1.362198,...,-0.575924,0.495889,1.154128,-0.016186,-2.079928,-0.554377,0.455179,0.001321,113.92,1.0
81186,58822,-4.384221,3.264665,-3.077158,3.403594,-1.938075,-1.221081,-3.310317,-1.111975,-1.977593,...,2.076383,-0.990303,-0.330358,0.158378,0.006351,-0.493860,-1.537652,-0.994022,45.64,1.0

In [21]:
new_df['Class'].value_counts()

Class
0.0    492
1.0    198
Name: count, dtype: int64

In [22]:
new_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,38782.638211,-0.370790,0.071244,0.619957,0.174419,-0.299087,0.081245,-0.090361,0.096289,0.049258,...,-0.002245,-0.007151,-0.095226,-0.036258,-0.011488,0.134113,-0.006836,-0.006499,-0.013606,84.059106
1.0,33363.156566,-6.471142,4.615004,-8.642655,5.163640,-4.726320,-1.982527,-6.839513,3.005157,-3.106588,...,0.381224,0.754921,-0.156429,-0.222226,-0.092181,0.229928,0.089311,0.568505,0.053900,93.992778

***Splitting the data into features and targets***

In [23]:
X = new_df.drop(columns='Class', axis=1)
Y = new_df['Class']

In [24]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
28617  35081  1.085832 -0.019862  1.411139  1.365234 -0.894725  0.092824
67912  52749  1.262254  0.321232  0.531876  0.610350 -0.392549 -0.968033
60324  49276  1.224487 -0.778533  0.780710 -0.783623 -1.140507 -0.060439
79322  57968 -6.463284 -7.325641  1.419325  0.701141  3.341705 -3.576497
70897  54066 -0.655794 -3.946605 -1.131316  0.431895 -2.082825 -0.711262
...      ...       ...       ...       ...       ...       ...       ...
79835  58199  0.340391  2.015233 -2.777330  3.812024 -0.461729 -1.152022
79874  58217 -0.443794  1.271395  1.206178  0.790371  0.418935 -0.848376
79883  58222 -1.322789  1.552768 -2.276921  2.992117 -1.947064 -0.480288
80760  58642 -0.451383  2.225147 -4.953050  4.342228 -3.656190 -0.020121
81186  58822 -4.384221  3.264665 -3.077158  3.403594 -1.938075 -1.221081

             V7        V8        V9  ...       V20       V21       V22  \
28617 -0.580158  0.165906  0.756434  ... -0.129443 -0.004530  0.261025
67912  0.126197 -0.259665 -0.099692  ... -0.032764 -0.247007 -0.666458
60324 -0.942140  0.165095 -0.824985  ...  0.134198  0.184507  0.341897
79322 -2.769595  0.980992  0.769910  ...  2.153279  0.722036 -0.692419
70897  1.093374 -0.489795 -0.703813  ...  1.579042  0.179981 -1.369590
...         ...       ...       ...  ...       ...       ...       ...
79835 -2.001959  0.548681 -2.344042  ...  0.326773  0.299769 -0.583283
79874  0.917691 -0.235511 -0.285692  ... -0.067205  0.119279  0.513479
79883 -1.362388  0.953242 -2.329629  ...  0.988493  0.614969 -0.195200
80760 -5.407554 -0.748436 -1.362198  ...  0.724381 -0.575924  0.495889
81186 -3.310317 -1.111975 -1.977593  ... -0.141533  2.076383 -0.990303

            V23       V24       V25       V26       V27       V28   Amount
28617  0.055842  0.417752  0.322363 -0.401656  0.094074  0.039769     9.99
67912  0.124896  0.400941  0.250625  0.091704 -0.022704  0.020946     1.29
60324  0.045176  0.027004  0.138127 -0.325971  0.030589  0.019471    50.00
79322  0.485653  0.721629 -0.338047  0.522230 -0.032016 -1.024053   224.32
70897 -0.928052  0.454545 -0.006432  0.982941 -0.279871  0.180625  1073.58
...         ...       ...       ...       ...       ...       ...      ...
79835 -0.187696 -0.329256  0.732328  0.058080  0.553143  0.318832     1.75
79874 -0.264243  0.443311  0.029516 -0.335141 -0.188815 -0.123391     5.09
79883  0.590711 -0.233378 -0.164285 -0.277498  0.428610  0.246394   270.00
80760  1.154128 -0.016186 -2.079928 -0.554377  0.455179  0.001321   113.92
81186 -0.330358  0.158378  0.006351 -0.493860 -1.537652 -0.994022    45.64

[690 rows x 30 columns]

In [25]:
print(Y)

28617    0.0
67912    0.0
60324    0.0
79322    0.0
70897    0.0
        ...
79835    1.0
79874    1.0
79883    1.0
80760    1.0
81186    1.0
Name: Class, Length: 690, dtype: float64

***Split the data into TRaining data & Testing data***

In [34]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.2, stratify=Y, random_state=2)

In [28]:
print(X.shape, X_train.shape, X_test.shape)

(690, 30) (552, 30) (138, 30)

In [37]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# Splitting data
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y,
    test_size=0.2,
    stratify=Y,
    random_state=2
)

print(X.shape, X_train.shape, X_test.shape)

# Feature scaling
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Model
model = LogisticRegression(max_iter=1000)

# Training
model.fit(X_train, Y_train)

(690, 30) (552, 30) (138, 30)

LogisticRegression(max_iter=1000)

In [38]:
model.fit(X_train, Y_train)

LogisticRegression(max_iter=1000)

***MoDel Evaluation based on accuracy Score***

In [42]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [44]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9746376811594203

***Accuracy on test DATA***

In [45]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [46]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.927536231884058